#!/usr/bin/env python
import os
import subprocess
import sys


def main():
    webms = [f for f in os.listdir('webm') if f[-5:] == '.webm']
    # write the javascript file
    with open('javascripts/404.js', 'w') as f:
        f.write('/*!\n')
        f.write(' * pick random webm\n')
        f.write(' */\n')
        f.write('\n')
        f.write('var webm = new Array();\n')
        i = 0
        for webm in webms:
            f.write('webm[{:d}] = "{}";\n'.format(i, webm))
            i += 1
        f.write('\n')
        f.write('var num = Math.floor(Math.random() * webm.length);\n')
        f.write('var thewebm = "\/webm/" + webm[num];\n')
        f.write('document.getElementById(\'mywebm\').src = thewebm;')

    # add new js to repo
    git_cmd_str = ["git", "add", "javascripts/404.js"]
    git_cmd = subprocess.Popen(git_cmd_str, stdout=subprocess.PIPE)
    git_out = git_cmd.communicate()[0]
    git_out = git_out.decode(sys.stdin.encoding)
    print(git_out)


if __name__ == '__main__':
    try:
        main()
    except:
        printf('Something is wrong with pre-commit hook!')
        sys.exit(1)
